export const API_KEYS = {
  GET_PETITIONS: "getPetitions",
  GET_SEARCH_PETITION: "searchPetitions",
  GET_SIGEND_PETITIONS: "getSignedPetitions",
  GET_CREATED_PETITIONS: "getCreatedPetitions",
  GET_APP_INFO: "getAppInfo",
  FETCH_USER: "fetchUser",
  GET_GENDER: "getGender",
  GET_ORGANIZATION: "getOrganization",
  GET_GOVERNORATE: "getGovernorate",
  LOGIN: "login",
  GET_PETITION_CATEGORY: "getPetitionCategory",
  GET_USER_FROM_ID: "getUserFromId",
  GET_PERSONAL_USERS_FROM_USER: "getPersonalUsersFromUsers",
  VERIFY_OTP: "verifyOtp",
}
